; PlatformIO Project Configuration File
; USB_freeD — 3D IMU Mouse using CodeCell C6 (ESP32-C6 + BNO085)

[env:codecell-c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_ESP32C6_DEV
lib_deps =
  https://github.com/microbotsio/CodeCell
